/* CREATE TABLE SecurityMaster (
	Id int IDENTITY(1,1) PRIMARY KEY,
	Security varchar(50),
	Description varchar(50),
	SecCCY varchar(50),
	SecuritySN varchar(50),
	CUSIP varchar(50),
	ISIN varchar(50),
	SEDOL varchar(50),
	OtherID varchar(50),
	BBGTicker varchar(50),
	SecurityType varchar(50),
	Exchange varchar(50),
	CompanySymbol varchar(50),
	Portfolio varchar(50),
	Sector varchar(50),
	Industry varchar(50),
	UserDef1 varchar(50),
	UserDef2 varchar(50),
	UserDef3 varchar(50),
	UserDef4 varchar(50),
	UserDef5 varchar(50),
	UserDef6 varchar(50),
	Country varchar(50),
	LongShort varchar(50),
	Quantity decimal(18,4),
	AvgPrice decimal(18,9),
	ClosePrice decimal(18,9),
	PriceProfit decimal(18,9),
	Interest decimal(18,4),
	Dividends decimal(18,4),
	Fees decimal(18,4),
	FxSettleToBase decimal(18,9),
	Value decimal(18,4),
	Exposure decimal(18,4),
	DayProfit decimal(18,4),
	Strategy varchar(50),
	TradeGroup varchar(50),
	AccrInt decimal(18,4),
	FutTotPrice decimal(18,4),
	PortfolioCCY varchar(50),
	PortfolioNav decimal(18,4),
	PrevMonthEndNav decimal(18,4),
	PrevDayNav decimal(18,4),
	LastPriceSource varchar(50),
	PosnDateInt int,
	ValuePCTofNAV decimal(18, 4),
	ChangePCT decimal(18,4),
	PCTofOutstanding decimal(18,4),
	MarketCap varchar(50),
	SharesOutstanding decimal(18,4),
	PreviousDayPrice decimal(18,4),
	ChangeNAVBPS decimal(18,4)
); */

/*

DROP TABLE CIQ;
CREATE TABLE CIQ(
	Id int IDENTITY(1,1) PRIMARY KEY,
	ticker varchar(25),
	cusip varchar(10),
	company_name varchar(100),
	sector varchar(25),
	beta decimal(18,8),
	dividend_yield decimal(18,8),
	trailing_pe decimal(18,8),
	forward_pe decimal(18,8),
	trailing_pb decimal(18,8),
	roe decimal(18,8),
	mkt_cap decimal(18,8),
	industry_sector varchar(25),
	industry_group varchar(50),
	beta_2y decimal(18,8),
	highest_single_day int,
	average int,
	ciq_description varchar(750),
	country varchar(20),
	security_type varchar(75),
	ciq_id varchar(20),
	country_name varchar(50),
	benchmark_index varchar(10)
);

SELECT * FROM asset_accrual

DROP TABLE asset_accrual;
CREATE TABLE asset_accrual(
	id int IDENTITY(1,1) PRIMARY KEY,
	account_number int,
	account_name varchar(50),
	account_type varchar(1),
	source_account_number int,
	source_account_name varchar(50),
	as_of_date date,
	mellon_security_id varchar(50),
	country_code varchar(2),
	country varchar(25),
	segment varchar(50),
	category varchar(50),
	sector varchar(50),
	industry varchar(50),
	security_description_1 varchar(100),
	security_description_2 varchar(100),
	acct_base_currency_code varchar(3),
	exchange_rate decimal(18,8),
	issue_currency_code varchar(3),
	shares_par decimal(18,8),
	base_cost decimal(18,8),
	local_cost decimal(18,8),
	base_price decimal(18,8),
	local_price decimal(18,8),
	base_market_value decimal(18,8),
	local_market_value decimal(18,8),
	base_net_income_recievable decimal(18,8),
	local_net_income_recievable decimal(18,8),
	base_market_value_with_accrual decimal(18,8),
	coupon_rate decimal(18,8),
	maturity_date date,
	base_unrealized_gain_loss decimal(18,8),
	local_unrealized_gain_loss decimal(18,8),
	base_unrealized_currency_gain_loss decimal(18,8),
	base_net_unrealized_gain_loss decimal(18,8),
	percent_of_total decimal(18,8),
	isin varchar(25),
	sedol varchar(25),
	cusip varchar(25),
	ticker varchar(10),
	cms_account_number int,
	income_currency varchar(3),
	security_identifier varchar(25),
	underlying_security varchar(25),
	fair_value_price_level int,
);

DROP TABLE duration_report;
CREATE TABLE duration_report(
	id int IDENTITY(1,1) PRIMARY KEY,
	security_number varchar(50),
	security_description varchar(100),
	cusip varchar(50),
	shares_outstanding decimal(18,8),
	asset_group varchar(2),
	traded_market_value_base decimal(18,8),
	maturity_date date,
	duration decimal(18,8),
	yield_to_maturity decimal(18,8),
	yield_current decimal(18,8),
	months_to_maturity int,
	days_to_maturity int
); */

DROP TABLE asset_info;
DROP TABLE asset_allocation;
DROP TABLE sector_allocation;
DROP TABLE currency_allocation;
DROP TABLE top_ten_holdings;
DROP TABLE geography_allocation;
DROP TABLE market_cap_allocation;

CREATE TABLE asset_info (
	id int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	fund_code int,
	fund_name varchar(100),
	total_nav decimal(18,2),
	beta decimal(18,12),
	active_share decimal(18,12),
	total_holdings int,
	current_yield decimal(18,16),
	yield_to_maturity decimal(18,16),
	modified_duration decimal(18,16),
	term_to_maturity decimal(18,16),
);

CREATE TABLE asset_allocation(
	id int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	fund_code int,
	fund_name varchar(100),
	asset_type varchar(50),
	asset_value decimal(6,4),
	asset_value_short decimal(6,4)
);

CREATE TABLE sector_allocation(
	id int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	fund_code int,
	fund_name varchar(100),
	sector_type varchar(50),
	sector_value decimal(6,4),
	sector_value_short decimal(6,4)
);


CREATE TABLE top_ten_holdings(
	id int IDENTITY(1,1) PRIMARY KEY,
	fund_name varchar(100),
	performance_date date,
	fund_code int,
	top_ten_holding varchar(100),
	holding_percent decimal(10,8),
	top_ten_percent decimal(10,8),
	ticker varchar(25),
	holding_description varchar(500)
);

CREATE TABLE currency_allocation(
	id int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	fund_code int,
	fund_name varchar(100),
	currency_type varchar(50),
	currency_value decimal(6,4),
	currency_value_short decimal(6,4)
);

CREATE TABLE geography_allocation(
	id int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	fund_code int,
	fund_name varchar(100),
	geography_type varchar(50),
	geography_value decimal(6,4),
	geography_value_short decimal(6,4)
);

CREATE TABLE market_cap_allocation(
	id int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	fund_code int,
	fund_name varchar(100),
	market_cap_type varchar(50),
	market_cap_value decimal(6,4),
	market_cap_value_short decimal(6,4)
);

/*
SELECT * FROM security_data WHERE OTHER_ID IN
  (SELECT OTHER_ID FROM security_data GROUP BY OTHER_ID HAVING COUNT(*) > 1)

CREATE TABLE security_data (
	Id int IDENTITY(1,1) PRIMARY KEY,
	SECURITY varchar(20), 
	SECURITY_SN varchar(50), 
	DESCRIPTION varchar(50),
	SEC_CCY varchar(3), 
	CUSIP varchar(20), 
	ISIN varchar(20), 
	SEDOL varchar(20), 
	OTHER_ID varchar(50), 
	BBG_TICKER varchar(50), 
	BLOOMBERG_EOD_TICKER varchar(50), 
	REFINITIV_DSS_TICKER varchar(50), 
	RIC varchar(50), 
	COMPANY_SYMBOL varchar(20), 
	CONTRACT_SIZE decimal(18,4), 
	COUNTRY varchar(20), 
	EXCHANGE varchar(20), 
	INDUSTRY varchar(20), 
	QUOTE_SIZE decimal(18,4), 
	SECTOR varchar(20), 
	SECURITY_TYPE varchar(20), 
	UNDERLYING_SN varchar(50), 
	USER_DEF1 varchar(20), 
	USER_DEF2 varchar(20), 
	USER_DEF3 varchar(20), 
	USER_DEF4 varchar(20), 
	USER_DEF5 varchar(20), 
	USER_DEF6 varchar(20), 
	COMPLIANCE_TAG1 varchar(20), 
	COMPLIANCE_TAG2 varchar(20), 
	COMPLIANCE_TAG3 varchar(20), 
	ISSUER_GROUP varchar(50), 
	COMPLIANCE_OVERRIDE varchar(50), 
	ISSUER_CLASSIFICATION varchar(50), 
	SECURITY_CLASSIFICATION varchar(50), 
	SHARES_OUTSTANDING decimal(18, 4), 
	SHARES_OUTSTANDING_LOCK int, 
	FACE_VALUE_OUTSTANDING decimal(18, 4), 
	FACE_VALUE_OUTSTANDING_LOCK int, 
	MARKET_CAP decimal(19, 4), 
	AVG_DAILY_VOLUME decimal(18, 4), 
	BETA decimal(18, 9), 
	DIVIDEND_AMOUNT decimal(18, 4), 
	DIVIDEND_EX_DATE_INT int, 
	DIVIDEND_PAYMENT_DATE_INT int, 
	ANNUALIZED_DIVIDEND decimal(18, 9), 
	EXPECTED_REPORT_DATE_INT int, 
	SHORT_INTEREST decimal(18, 4), 
	EQUITY_FLOAT decimal(18, 4), 
	VOLATILITY decimal(18, 9), 
	USER_DEFINED_NUMBER1 decimal(18, 4),
	USER_DEFINED_NUMBER2 decimal(18, 4), 
	USER_DEFINED_NUMBER3 decimal(18, 4), 
	USER_DEFINED_NUMBER4 decimal(18, 4), 
	USER_DEFINED_NUMBER5 decimal(18, 4), 
	USER_DEFINED_NUMBER6 decimal(18, 4), 
	USER_DEFINED_NUMBER7 decimal(18, 4), 
	USER_DEFINED_NUMBER8 decimal(18, 4), 
	USER_DEFINED_NUMBER9 decimal(18, 4), 
	USER_DEFINED_STRING1 varchar(50), 
	USER_DEFINED_STRING2 varchar(50), 
	USER_DEFINED_STRING3 varchar(50), 
	TS datetime, 
	LAST_UPDATE_ID varchar(50),
	PCT_OF_OUTSTANDING decimal(18, 4)
);

CREATE TABLE AlphaDeskImport (
	Id int IDENTITY(1,1) PRIMARY KEY,
	Security varchar(50),
	Description varchar(50),
	SecCCY varchar(50),
	SecuritySN varchar(50),
	CUSIP varchar(50),
	ISIN varchar(50),
	SEDOL varchar(50),
	OtherID varchar(50),
	BBGTicker varchar(50), 
	RIC varchar(50),
	SecurityType varchar(50),
	Exchange varchar(50),
	QuoteSize decimal(18,4),
	ContractSize decimal(18,4),
	UnderlyingSN varchar(50),
	CompanySymbol varchar(50),
	Sector varchar(50),
	Industry varchar(50),
	UserDef1 varchar(50),
	UserDef2 varchar(50),
	UserDef3 varchar(50),
	UserDef4 varchar(50),
	UserDef5 varchar(50),
	UserDef6 varchar(50),
	Country varchar(50),
	PriceSource int,
	PosnDate int,
	LongShort varchar(50),
	Quantity decimal(18,4),
	AvgPrice decimal(18,9),
	ClosePrice decimal(18,9),
	PriceProfit decimal(18,9),
	Interest decimal(18,4),
	Dividends decimal(18,4),
	Fees decimal(18,4),
	FxSettleToBase decimal(18,9),
	Value decimal(18,4),
	Exposure decimal(18,4),
	DayProfit decimal(18,4),
	Subscriptions decimal(18,4),
	Strategy varchar(50),
	Owner varchar(50),
	TradeGroup varchar(50),
	UserGroup1 varchar(50),
	UserGroup2 varchar(50),
	UserGroup3 varchar(50),
	PosnStatus varchar(50),
	FxExposureLoc decimal(18,4),
	DayFxProfit decimal(18,4),
	FxSecurityToBase decimal(18,9),
	FxBaseToDenom decimal(18,9),
	AccrInt decimal(18,4),
	FutTotPrice decimal(18,4),
	PosnOpenDt int,
	PosnCloseDt int,
	AccountId int,
	Account varchar(50),
	AccountDescription varchar(50),
	Portfolio varchar(50),
	PortfolioDescription varchar(50),
	PortfolioCCY varchar(50),
	PortfolioNav decimal(18,4),
	PortfolioTransfer decimal(18,4),
	PrevDayNav decimal(18,4),
	PrevMonthEndNav decimal(18,4),
	PosnDateInt int,
	PrevPosnDateInt int,
	PrevMonthEndInt int,
	PosnMonth varchar(50),
	IssuerGroup varchar(50),
	ComplianceOverride varchar(50),
	IssuerClassification varchar(50),
	SecurityClasification varchar(50),
	AccountNumber varchar(50),
	LastPriceSource varchar(50),
	ManualPrice decimal(18,9),
	SpreadSource varchar(50),
	ManualSpread decimal(18,9),
	UnderlyingSecurity varchar(50),
	UnderlyingDescription varchar(50),
	UnderlyingSecCCY varchar(50),
	UnderlyingCUSIP varchar(50),
	UnderlyingISN varchar(50),
	UnderlyingSEDOL varchar(50),
	UnderlyingOtherId varchar(50),
	UnderlyingExchange varchar(50),
	UnderlyingQuoteSize decimal(18,4),
	UnderlyingContractSize decimal(18,4),
	UnderlyingCompanySymbol varchar(50),
	UnderlyingSector varchar(50),
	UnderlyingIndustry varchar(50),
	UnderlyingUserDef1 varchar(50),
	UnderlyingUserDef2 varchar(50),
	UnderlyingUserDef3 varchar(50),
	UnderlyingUserDef4 varchar(50),
	UnderlyingUserDef5 varchar(50),
	UnderlyingUserDef6 varchar(50),
	UnderlyingCountry varchar(50),
	UnderlyingPriceSource int
); */
