DROP TABLE ftse_constituent

CREATE TABLE ftse_constituent (
	ID int IDENTITY(1,1) PRIMARY KEY,
	mucid int,
	price decimal(18,8),
	accrued_interest decimal(18,8),
	adjusted_face_value decimal(38,8),
	adj_face_value_orig_par decimal(38,0),
	market_weight decimal(18,8),
	par_weight decimal(18,8),
	industry_sector varchar(50),
	industry_group varchar(50),
	industry_sub_group varchar(50),
	term varchar(10),
	cusip varchar(10),
	issuer_name varchar(50),
	maturity_date date,
	eff_mat_date date,
	yield decimal(18,10),
	annual_coupon_rate decimal(18,8),
	d_val_01 decimal(18,8),
	performance_date date,
	mac_duration decimal(18,8),
	mod_duration decimal(18,8),
	convexity decimal(18,8),
	rating varchar(4),
	term_to_maturity decimal(18,8),
	market_value decimal(38,8),
	isin varchar(15),
	country varchar(3),
	issue_date date,
	first_payment_date date,
	next_call_date date,
	nvcc_flag varchar(1),
	lrcn_at1_flag varchar(1),
	green_bond_flag varchar(1),
	social_bond_flag varchar(1),
	sustainability_bond_flag varchar(1),
	slb_flag varchar(1),
	snapshot_time time,
	currency varchar(3),
	direct_perm_id decimal(38,0),
	npi_perm_id decimal(38,0),
	ultimate_parent_perm_id decimal(38,0),
	economic_sector_code int,
	economic_sector_desc varchar(100),
	business_sector_code int,
	business_sector_desc varchar(100),
	industry_group_code int,
	industry_group_desc varchar(100),
	industry_code int,
	industy_desc varchar(100),
	activity_code decimal(38,0),
	activity_desc varchar(100),
	curve_spread_canyc decimal(18,8),
	spread_to_benchmark decimal(18,8),
	benchmark_cusip varchar(10),
	ytw decimal(18,8),
	workout_date date,
	oas_spread decimal(18,8),
	oas_mod_duration decimal(18,8),
	oas_convexity decimal(18,8),
	effective_duration decimal(18,8),
	effective_convexity decimal(18,8),
	rpb_factor decimal(18,8),
	krd_0_25 decimal(18,8),
	krd_0_50 decimal(18,8),
	krd_0_75 decimal(18,8),
	krd_1 decimal(18,8),
	krd_2 decimal(18,8),
	krd_3 decimal(18,8),
	krd_4 decimal(18,8),
	krd_5 decimal(18,8),
	krd_7 decimal(18,8),
	krd_10 decimal(18,8),
	krd_12 decimal(18,8),
	krd_15 decimal(18,8),
	krd_20 decimal(18,8),
	krd_25 decimal(18,8),
	krd_30 decimal(18,8),
	excess_return decimal(18,8),
	price_return decimal(18,8),
	total_return decimal(18,8)
);

DROP TABLE ftse_returns;

CREATE TABLE ftse_returns(
	ID int IDENTITY(1,1) PRIMARY KEY,
	mucid int,
	ending_date date,
	price_return decimal(18,8),
	total_return decimal(18,8)
);

DROP TABLE ftse_index;

CREATE TABLE ftse_index_basic(
	ID int IDENTITY(1,1) PRIMARY KEY,
	mucid int,
	cusip varchar(10),
	issuer_name varchar(50),
	annual_coupon_rate decimal(18,8),
	maturity_date date,
	eff_mat_date date,
	industry_sector varchar(50),
	industry_group varchar(50),
	industry_sub_group varchar(50),
	term varchar(10),
	rating varchar(4),
	adjusted_face_value decimal(38,8),
	adj_face_value_orig_par decimal(38,0),
	market_weight decimal(18,8),
	par_weight decimal(18,8),
	beginning_date date,
	perfromance_date date,
	price_return decimal(18,8),
	total_return decimal(18,8)
)

DROP TABLE ftse_index_tier_1;

CREATE TABLE ftse_index_tier_1 (
	ID int IDENTITY(1,1) PRIMARY KEY,
	performance_date date,
	index_id int,
	index_name varchar(100),
	average_yield decimal(18,8),
	price_index decimal(18,8),
	total_return decimal(18,8),
	sector_weight decimal(18,8),
	term_weight decimal(18,8),
	macaulay_duration decimal(18,8),
	modified_duration decimal(18,8),
	value_of_01 decimal(18,8),
	average_coupon decimal(18,8),
	average_term decimal(18,8),
	convexity decimal(18,8),
	industry_sector varchar(50),
	industry_group varchar(50),
	rating varchar(5),
	term varchar(10),
	index_type varchar(10),
	average_rating varchar(4),
	number_of_bonds int,
	total_market_value decimal(38,8),
	total_par_amount decimal(38,8),
	month_to_date_return decimal(18,8),
	year_to_date_return decimal(18,8),
	last_3_months_return decimal(18,8),
	last_6_months_return decimal(18,8),
	last_1_year_return decimal(18,8),
	last_3_years_return decimal(18,8),
	last_5_years_return decimal(18,8),
	last_10_years_return decimal(18,8),
	daily_turnover decimal(18,8),
	snapshot_time time,
	currency varchar(4)
);

DROP TABLE ice_constituent;

CREATE TABLE ice_constituent (
	ID int IDENTITY(1,1) PRIMARY KEY,
	index_name varchar(10),
	performance_date date,
	cusip varchar(10),
	isin_number varchar(15),
	index_description varchar(200),
	maturity_date date,
	issue_date date,
	par_amount decimal(18,8),
	convexity decimal(18,8),
	current_yield decimal(18,8),
	current_coupon decimal(18,8),
	eff_duration decimal(18,8),
	macaulay_duration decimal(18,8),
	modified_duration decimal(18,8),
	spread_duration decimal(18,8),
	rating varchar(5),
	accrued_interest decimal(18,8),
	cash decimal(18,8),
	price decimal(18,8),
	full_market_value_loc decimal(18,8),
	total_market_value decimal(18,8),
	market_weight decimal(18,8),
	oas int,
	yield_to_maturity decimal(18,8),
	prr_1_day_loc decimal(18,8),
	prr_index_val_loc decimal(18,8),
	trr_1_day_loc decimal(18,8),
	prr_1_day_usd_u decimal(18,8),
	prr_1_day_cad_u decimal(18,8),
	trr_1_day_usd_u decimal(18,8),
	trr_1_day_cad_u decimal(18,8),
	semi_yield_to_worst decimal(18,8),
	rating_middle_of_three varchar(5),
);

DROP TABLE ice
CREATE TABLE ice (
	ID int IDENTITY(1,1) PRIMARY KEY,
	index_name varchar(5),
	as_of_date date,
	cusip varchar(10),
	isin_number varchar(12),
	mkt_percent_index_wght decimal(18,6),
	maturity_date date,
	issue_date date,
	par_ammount decimal(18,4),
	convexity decimal(18,4),
	eff_dur decimal(18,4),
	macaulay_dur decimal(18,4),
	modified_dur decimal(18,4),
	spread_duration decimal(18,4),
	rating varchar(4),
	accrued_interest decimal(18,6),
	cash decimal(18,6),
	price decimal(18,6),
	full_market_value_loc decimal(18,6),
	oas int,
	yld_to_maturity decimal(18,4),
	prr_percent_1_day_loc decimal(18,4),
	prr_index_val_loc decimal(18,4),
	trr_percent_1_day_loc decimal(18,4),
	ml_industry_1 varchar(50),
	ml_industry_2 varchar(50),
	ml_industry_3 varchar(50),
	ml_industry_4 varchar(50),
	ml_ind_1_code varchar(4),
	ml_ind_2_code varchar(4),
	ml_ind_3_code varchar(4),
	ml_ind_4_code varchar(4),
	trr_percent_12_month_cad_h decimal(18,4),
	trr_percent_12_month_cad_u decimal(18,4),
	trr_index_val_cad_u decimal(18,4),
	trr_percent_1_day_cad_u decimal(18,4),
	trr_percent_1_week_cad_u decimal(18,4),
	trr_percent_mtd_cad_u decimal(18,4),
);

DROP TABLE moody_to_sap_conv;
CREATE TABLE moody_to_sap_conv(
	moody_rating varchar(10) PRIMARY KEY,
	sap_rating varchar(10)
)
INSERT INTO moody_to_sap_conv(moody_rating, sap_rating)
VALUES
('AAA','AAA'),
('AA1','AA+'),
('AA2','AA'),
('AA3','AA-'),
('A1','A+'),
('A2','A'),
('A3','A-'),
('BBB1','BBB+'),
('BBB2','BBB'),
('BBB3','BBB-'),
('BB1','BB+'),
('BB2','BB'),
('BB3','BB-'),
('B1','B+'),
('B2','B'),
('B3','B-'),
('CCC1','CCC+'),
('CCC2','CCC'),
('CCC3','CCC-'),
('CC','CC'),
('C','C'),
('D','D'),
('CASH','CASH'),
('"Blanks"','Unrated')